project:
  type: website

website:
  title: "Laelis_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: lumen
    css: styles.css



